# ClaudeBench shaderpack
separateAo=true
oldLighting=false
oldHandLight=false
underwaterOverlay=false
vignette=false
sun=false
moon=true
clouds=off
particles.before.deferred=true
dynamicHandLight=true
shadowTerrain=true
shadowTranslucent=true
shadowEntities=true
shadowBlockEntities=true
customTexture.cloudNoise=textures/cloudnoise.dat TEXTURE_3D RGBA16 64 64 64 RGBA UNSIGNED_SHORT
