// Internal compiled kernel choices. These constants have no Iris allowed-value annotations.
// Ultra keeps the accepted sampling budgets; lower tiers change the integration kernels.
#ifndef PERFORMANCE_QUALITY_INCLUDED
#define PERFORMANCE_QUALITY_INCLUDED

#if PERFORMANCE_PROFILE >= 4
#define SHADOW_BLOCKER_SAMPLES 6
#define REFLECTION_STEPS 28
#define REFLECTION_REFINEMENT 6
#define WATER_WAVE_OCTAVES 4
#define WATER_CLOUD_REFLECTION_QUALITY 2
#define VL_NEAR_STEPS 16
#define VL_FAR_STEPS 10
#define END_STORM_STEPS 16
#define BLOOM_QUALITY 3
#define SUN_RAY_SAMPLES 48
#define POSTFX_ENABLED 1
#define VANILLA_LIGHTING 0
#define SSAO_SAMPLES 8
#define CLOUD_LIGHT_QUALITY 3
#define CLOUD_MARCH_SCALE 1.0
#define CLOUD_DETAIL_QUALITY 2
#define SKY_QUALITY 3
#define NIGHT_DETAIL_QUALITY 2
#elif PERFORMANCE_PROFILE == 3
#define SHADOW_BLOCKER_SAMPLES 4
#define REFLECTION_STEPS 20
#define REFLECTION_REFINEMENT 5
#define WATER_WAVE_OCTAVES 3
#define WATER_CLOUD_REFLECTION_QUALITY 2
#define VL_NEAR_STEPS 12
#define VL_FAR_STEPS 8
#define END_STORM_STEPS 12
#define BLOOM_QUALITY 2
#define SUN_RAY_SAMPLES 32
#define POSTFX_ENABLED 1
#define VANILLA_LIGHTING 0
#define SSAO_SAMPLES 6
#define CLOUD_LIGHT_QUALITY 3
#define CLOUD_MARCH_SCALE 1.0
#define CLOUD_DETAIL_QUALITY 2
#define SKY_QUALITY 2
#define NIGHT_DETAIL_QUALITY 2
#elif PERFORMANCE_PROFILE == 2
#define SHADOW_BLOCKER_SAMPLES 3
#define REFLECTION_STEPS 14
#define REFLECTION_REFINEMENT 4
#define WATER_WAVE_OCTAVES 2
#define WATER_CLOUD_REFLECTION_QUALITY 1
#define VL_NEAR_STEPS 8
#define VL_FAR_STEPS 5
#define END_STORM_STEPS 8
#define BLOOM_QUALITY 1
#define SUN_RAY_SAMPLES 20
#define POSTFX_ENABLED 1
#define VANILLA_LIGHTING 0
#define SSAO_SAMPLES 4
#define CLOUD_LIGHT_QUALITY 2
#define CLOUD_MARCH_SCALE 1.35
#define CLOUD_DETAIL_QUALITY 1
#define SKY_QUALITY 1
#define NIGHT_DETAIL_QUALITY 1
#elif PERFORMANCE_PROFILE == 1
#define SHADOW_BLOCKER_SAMPLES 0
#define REFLECTION_STEPS 0
#define REFLECTION_REFINEMENT 0
#define WATER_WAVE_OCTAVES 1
#define WATER_CLOUD_REFLECTION_QUALITY 0
#define VL_NEAR_STEPS 4
#define VL_FAR_STEPS 3
#define END_STORM_STEPS 4
#define BLOOM_QUALITY 0
#define SUN_RAY_SAMPLES 0
#define POSTFX_ENABLED 1
#define VANILLA_LIGHTING 0
#define SSAO_SAMPLES 2
#define CLOUD_LIGHT_QUALITY 1
#define CLOUD_MARCH_SCALE 1.8
#define CLOUD_DETAIL_QUALITY 1
#define SKY_QUALITY 1
#define NIGHT_DETAIL_QUALITY 1
#else
#define SHADOW_BLOCKER_SAMPLES 0
#define REFLECTION_STEPS 0
#define REFLECTION_REFINEMENT 0
#define WATER_WAVE_OCTAVES 0
#define WATER_CLOUD_REFLECTION_QUALITY 0
#define VL_NEAR_STEPS 0
#define VL_FAR_STEPS 0
#define END_STORM_STEPS 0
#define BLOOM_QUALITY 0
#define SUN_RAY_SAMPLES 0
#define POSTFX_ENABLED 0
#define VANILLA_LIGHTING 1
#define SSAO_SAMPLES 0
#define CLOUD_LIGHT_QUALITY 0
#define CLOUD_MARCH_SCALE 1.0
#define CLOUD_DETAIL_QUALITY 0
#define SKY_QUALITY 0
#define NIGHT_DETAIL_QUALITY 0
#endif

// Potato uses Minecraft lightmap sRGB, no allocated voxel field or HDR histories.
#if PERFORMANCE_PROFILE == 0
#undef LIGHT_FIELD
#undef VOLUMETRIC_LIGHT
#undef WATER_SSR
#undef TAA
#endif

#endif
